Repository rt-net/sciurus17_ros, pull requests merged in 2023-09, with the labels that each got.

#133 package.xmlのversionタグを1.0.0に更新
  sciurus17/package.xml
  sciurus17_bringup/package.xml
  sciurus17_control/package.xml
  sciurus17_description/package.xml
  sciurus17_examples/package.xml
  sciurus17_gazebo/package.xml
  sciurus17_moveit_config/package.xml
  sciurus17_msgs/package.xml
  sciurus17_tools/package.xml
  sciurus17_vision/package.xml
Labels: Type: Maintenance

#136 Apache-2.0ライセンスを適用。バージョンを2.0.0に更新。
  CONTRIBUTING.md
  LICENSE
  README.en.md
  README.md
  sciurus17/package.xml
  sciurus17_bringup/package.xml
  sciurus17_control/package.xml
  sciurus17_examples/package.xml
  sciurus17_examples/scripts/box_stacking_example.py
  sciurus17_examples/scripts/chest_camera_tracking.py
  sciurus17_examples/scripts/control_effort_wrist.py
  sciurus17_examples/scripts/depth_camera_tracking.py
  sciurus17_examples/scripts/gripper_action_example.py
  sciurus17_examples/scripts/hand_position_publisher_example.py
  sciurus17_examples/scripts/head_camera_tracking.py
  sciurus17_examples/scripts/neck_joint_trajectory_example.py
  sciurus17_examples/scripts/pick_and_place_left_arm_demo.py
  sciurus17_examples/scripts/pick_and_place_right_arm_demo.py
  sciurus17_examples/scripts/pick_and_place_two_arm_demo.py
  sciurus17_examples/scripts/preset_pid_gain_example.py
  sciurus17_examples/scripts/waist_joint_trajectory_example.py
  sciurus17_examples/src/object_detection.cpp
  sciurus17_gazebo/package.xml
  sciurus17_moveit_config/package.xml
  sciurus17_msgs/package.xml
  sciurus17_tools/package.xml
  sciurus17_vision/package.xml
Labels: Type: Breaking Change, Type: Maintenance

#138 Add image_pipeline dependency to package.xml
  sciurus17_vision/package.xml
Labels: Type: Bug

#139 READMEに簡易シミュレータに関する記述を追加
  sciurus17_examples/README.md
Labels: Type: Documentation
